/** @type {import('tailwindcss').Config} */
export default {
        content: [
                "./index.html",
                "./src/**/*.{js,ts,jsx,tsx}",
        ],
        theme: {
                extend: {
                        colors: {
                                primary: {
                                        50: '#eff6ff',
                                        100: '#dbeafe',
                                        200: '#bfdbfe',
                                        300: '#93c5fd',
                                        400: '#60a5fa',
                                        500: '#3b82f6',
                                        600: '#2563eb',
                                        700: '#1d4ed8',
                                        800: '#1e40af',
                                        900: '#1e3a8a',
                                        950: '#172554',
                                },
                                accent: {
                                        50: '#eef2ff',
                                        100: '#e0e7ff',
                                        200: '#c7d2fe',
                                        300: '#a5b4fc',
                                        400: '#818cf8',
                                        500: '#6366f1',
                                        600: '#4f46e5',
                                        700: '#4338ca',
                                        800: '#3730a3',
                                        900: '#312e81',
                                        950: '#1e1b4b',
                                },
                                success: {
                                        50: '#f0fdf4',
                                        100: '#dcfce7',
                                        200: '#bbf7d0',
                                        300: '#86efac',
                                        400: '#4ade80',
                                        500: '#22c55e',
                                        600: '#16a34a',
                                        700: '#15803d',
                                        800: '#166534',
                                        900: '#14532d',
                                },
                                danger: {
                                        50: '#fef2f2',
                                        100: '#fee2e2',
                                        200: '#fecaca',
                                        300: '#fca5a5',
                                        400: '#f87171',
                                        500: '#ef4444',
                                        600: '#dc2626',
                                        700: '#b91c1c',
                                        800: '#991b1b',
                                        900: '#7f1d1d',
                                },
                                warning: {
                                        50: '#fffbeb',
                                        100: '#fef3c7',
                                        200: '#fde68a',
                                        300: '#fcd34d',
                                        400: '#fbbf24',
                                        500: '#f59e0b',
                                        600: '#d97706',
                                        700: '#b45309',
                                        800: '#92400e',
                                        900: '#78350f',
                                },
                                surface: {
                                        50: '#fafafa',
                                        100: '#f4f4f5',
                                        200: '#e4e4e7',
                                        300: '#d4d4d8',
                                        400: '#a1a1aa',
                                        500: '#71717a',
                                        600: '#52525b',
                                        700: '#3f3f46',
                                        800: '#27272a',
                                        900: '#18181b',
                                }
                        },
                        fontFamily: {
                                sans: ['Inter', 'system-ui', 'sans-serif'],
                        },
                        animation: {
                                'fade-in': 'fadeIn 0.3s ease-out',
                                'fade-in-up': 'fadeInUp 0.4s ease-out',
                                'fade-in-down': 'fadeInDown 0.4s ease-out',
                                'slide-in-left': 'slideInLeft 0.3s ease-out',
                                'slide-in-right': 'slideInRight 0.3s ease-out',
                                'scale-in': 'scaleIn 0.2s ease-out',
                                'bounce-in': 'bounceIn 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55)',
                                'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
                                'shimmer': 'shimmer 1.5s infinite',
                                'spin-slow': 'spin 3s linear infinite',
                        },
                        keyframes: {
                                fadeIn: {
                                        '0%': { opacity: '0' },
                                        '100%': { opacity: '1' },
                                },
                                fadeInUp: {
                                        '0%': { opacity: '0', transform: 'translateY(10px)' },
                                        '100%': { opacity: '1', transform: 'translateY(0)' },
                                },
                                fadeInDown: {
                                        '0%': { opacity: '0', transform: 'translateY(-10px)' },
                                        '100%': { opacity: '1', transform: 'translateY(0)' },
                                },
                                slideInLeft: {
                                        '0%': { opacity: '0', transform: 'translateX(-20px)' },
                                        '100%': { opacity: '1', transform: 'translateX(0)' },
                                },
                                slideInRight: {
                                        '0%': { opacity: '0', transform: 'translateX(20px)' },
                                        '100%': { opacity: '1', transform: 'translateX(0)' },
                                },
                                scaleIn: {
                                        '0%': { opacity: '0', transform: 'scale(0.95)' },
                                        '100%': { opacity: '1', transform: 'scale(1)' },
                                },
                                bounceIn: {
                                        '0%': { opacity: '0', transform: 'scale(0.3)' },
                                        '50%': { transform: 'scale(1.05)' },
                                        '70%': { transform: 'scale(0.9)' },
                                        '100%': { opacity: '1', transform: 'scale(1)' },
                                },
                                pulseSoft: {
                                        '0%, 100%': { opacity: '1' },
                                        '50%': { opacity: '0.7' },
                                },
                                shimmer: {
                                        '0%': { backgroundPosition: '-200% 0' },
                                        '100%': { backgroundPosition: '200% 0' },
                                },
                        },
                        transitionTimingFunction: {
                                'ease-spring': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
                                'ease-snap': 'cubic-bezier(0.85, 0, 0.15, 1)',
                        },
                        backdropBlur: {
                                xs: '2px',
                        },
                        boxShadow: {
                                'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
                                'soft-lg': '0 10px 40px -15px rgba(0, 0, 0, 0.1)',
                                'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
                                'glow-primary': '0 0 20px rgba(59, 130, 246, 0.3)',
                                'glow-success': '0 0 20px rgba(34, 197, 94, 0.3)',
                                'glow-danger': '0 0 20px rgba(239, 68, 68, 0.3)',
                        },
                        borderRadius: {
                                '4xl': '2rem',
                        },
                },
        },
        plugins: [],
}
